# Generated by Django 4.2.3 on 2026-04-18 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0002_choice_submission_question_choice_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
